package com.project.settings;

public class GithubLogin {
	
	//This token is generated by  Go to your github account Settings > Developer Settings > Personal Access Tokens, add token here
	public static String  userName="Add Github token here"; 
	 

}
